# Generated by Django 6.0.3 on 2026-03-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=32, verbose_name='Логин')),
                ('password', models.CharField(max_length=16, verbose_name='Пароль')),
                ('score', models.IntegerField(verbose_name='Очки')),
            ],
        ),
    ]
