# Generated by Django 6.0.3 on 2026-03-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователь'},
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Очки'),
        ),
    ]
