# Generated by Django 6.0.3 on 2026-03-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_api', '0002_alter_user_options_alter_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=32, unique=True, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.FloatField(default=0, verbose_name='Очки'),
        ),
    ]
