# Generated by Django 6.0.3 on 2026-03-07 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_api', '0003_alter_user_login_alter_user_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('life_duration', models.IntegerField(verbose_name='Продолжительность жизни (в годах)')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('age', models.IntegerField(default=0, verbose_name='Возраст')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clicker_api.kind', verbose_name='Вид')),
            ],
        ),
    ]
