# Generated by Django 6.0.3 on 2026-03-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_api', '0004_kind_animal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'животное', 'verbose_name_plural': 'Животные'},
        ),
        migrations.AlterModelOptions(
            name='kind',
            options={'verbose_name': 'вид', 'verbose_name_plural': 'Виды'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
