# Generated by Django 6.0.3 on 2026-03-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_api', '0005_alter_animal_options_alter_kind_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='clicker_api.user', verbose_name='Владелец'),
        ),
    ]
