# Generated by Django 6.0.3 on 2026-03-07 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_api', '0006_animal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clicker_api.user', verbose_name='Владелец'),
        ),
    ]
