# Generated by Django 6.0.3 on 2026-03-07 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clicker_api', '0007_alter_animal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'имя',
                'verbose_name_plural': 'Имена',
            },
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clicker_api.name', verbose_name='Имя'),
        ),
    ]
